/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractOptions, Options } from 'web3-eth-contract';
import { Block } from 'web3-eth';
import { EventLog } from 'web3-core';
import { EventEmitter } from 'events';
import { Callback, TransactionObject } from './types';

export class Migrations extends Contract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  );
  methods: {
    setCompleted(completed: number | string): TransactionObject<void>;

    upgrade(new_address: string): TransactionObject<void>;

    last_completed_migration(): TransactionObject<string>;
    owner(): TransactionObject<string>;
  };
  events: {
    allEvents: (
      options?: {
        filter?: object;
        fromBlock?: number | string;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
}
