/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import Contract, { CustomOptions, contractOptions } from 'web3/eth/contract';
import { TransactionObject, BlockType } from 'web3/eth/types';
import { Callback, EventLog } from 'web3/types';
import { EventEmitter } from 'events';
import { Provider } from 'web3/providers';

export class Survey {
  constructor(jsonInterface: any[], address?: string, options?: CustomOptions);
  _address: string;
  options: contractOptions;
  methods: {
    survey_indices(arg0: number | string): TransactionObject<string>;

    Surveys(
      arg0: string | number[]
    ): TransactionObject<{
      amount: string;
      requiredResponses: string;
      surveyOwner: string;
      creationTime: string;
      expirationTime: string;
      name: string;
      hash: string;
      tokenAddress: string;
      open: boolean;
      remainingAmount: string;
      responsesHash: string;
      totalResponses: string;
      0: string;
      1: string;
      2: string;
      3: string;
      4: string;
      5: string;
      6: string;
      7: string;
      8: boolean;
      9: string;
      10: string;
      11: string;
    }>;

    bytes32ToString(x: string | number[]): TransactionObject<string>;

    createSurvey(
      _name: string,
      _amount: number | string,
      _requiredResponses: number | string,
      _tokenAddress: string,
      _expirationTime: number | string,
      _hash: string
    ): TransactionObject<boolean>;

    submitSurveyResponse(
      _name: string,
      _responseHash: string,
      _responsesHash: string
    ): TransactionObject<boolean>;

    surveyInfo(
      _name: string
    ): TransactionObject<{
      0: string;
      1: string;
      2: string;
      3: string;
    }>;

    _surveyInfo(
      index: string | number[]
    ): TransactionObject<{
      0: string;
      1: string;
      2: string;
      3: string;
    }>;

    getUserSurveys(
      _surveyOwner: string
    ): TransactionObject<{
      0: (string)[];
      1: (string)[];
    }>;

    strToMappingIndex(str: string): TransactionObject<string>;

    stringToBytes32(source: string): TransactionObject<string>;

    bytes32ArrayToString(
      data: (string | number[])[]
    ): TransactionObject<string>;

    numSurveys(): TransactionObject<string>;
  };
  deploy(options: {
    data: string;
    arguments: any[];
  }): TransactionObject<Contract>;
  events: {
    allEvents: (
      options?: {
        filter?: object;
        fromBlock?: BlockType;
        topics?: (null | string)[];
      },
      cb?: Callback<EventLog>
    ) => EventEmitter;
  };
  getPastEvents(
    event: string,
    options?: {
      filter?: object;
      fromBlock?: BlockType;
      toBlock?: BlockType;
      topics?: (null | string)[];
    },
    cb?: Callback<EventLog[]>
  ): Promise<EventLog[]>;
  setProvider(provider: Provider): void;
}
